// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectWasel.Data;

#nullable disable

namespace ProjectWasel.Migrations
{
    [DbContext(typeof(WaselContext))]
    [Migration("20260411164648_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectWasel.Models.Checkpoint", b =>
                {
                    b.Property<int>("CheckpointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckpointId"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CheckpointId");

                    b.ToTable("Checkpoints");

                    b.HasData(
                        new
                        {
                            CheckpointId = 1,
                            LastUpdated = new DateTime(2026, 4, 11, 16, 46, 48, 452, DateTimeKind.Utc).AddTicks(4070),
                            Latitude = 31.9539m,
                            Longitude = 35.2061m,
                            Name = "Qalandia",
                            Status = "active"
                        },
                        new
                        {
                            CheckpointId = 2,
                            LastUpdated = new DateTime(2026, 4, 11, 16, 46, 48, 452, DateTimeKind.Utc).AddTicks(4070),
                            Latitude = 31.7054m,
                            Longitude = 35.2024m,
                            Name = "Bethlehem",
                            Status = "active"
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.CheckpointStatusHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CheckpointId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HistoryId");

                    b.HasIndex("CheckpointId");

                    b.ToTable("CheckpointStatusHistories");

                    b.HasData(
                        new
                        {
                            HistoryId = 1,
                            ChangedAt = new DateTime(2026, 4, 11, 16, 46, 48, 452, DateTimeKind.Utc).AddTicks(4070),
                            CheckpointId = 1,
                            Status = "active"
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.ExternalData", b =>
                {
                    b.Property<int>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DataId"));

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DataId");

                    b.ToTable("ExternalData");

                    b.HasData(
                        new
                        {
                            DataId = 1,
                            ExternalKey = "weather_qalandia",
                            FetchedAt = new DateTime(2026, 4, 11, 16, 46, 48, 452, DateTimeKind.Utc).AddTicks(4070),
                            JsonData = "{\"temp\":25}",
                            Source = "WeatherAPI"
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentId"));

                    b.Property<int?>("CheckpointId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("IncidentId");

                    b.HasIndex("CheckpointId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            IncidentId = 1,
                            CheckpointId = 1,
                            CreatedAt = new DateTime(2026, 4, 11, 16, 46, 48, 452, DateTimeKind.Utc).AddTicks(4070),
                            CreatedByUserId = 3,
                            Description = "Car accident",
                            Severity = "low",
                            Status = "verified",
                            Title = "Accident",
                            Type = "accident",
                            UpdatedAt = new DateTime(2026, 4, 11, 16, 46, 48, 452, DateTimeKind.Utc).AddTicks(4070)
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ProjectWasel.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IncidentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Votes")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            ReportId = 1,
                            Category = "Accident",
                            CreatedAt = new DateTime(2026, 4, 11, 16, 46, 48, 452, DateTimeKind.Utc).AddTicks(4070),
                            Description = "Saw accident",
                            IncidentId = 1,
                            Latitude = 31.9539m,
                            Longitude = 35.2061m,
                            Status = 1,
                            Timestamp = new DateTime(2026, 4, 11, 16, 46, 48, 452, DateTimeKind.Utc).AddTicks(4070),
                            UserId = 3,
                            Votes = 5
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.ReportAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModeratorId")
                        .HasColumnType("int");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorId");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportAuditLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Approve",
                            ActionDate = new DateTime(2026, 4, 11, 16, 46, 48, 452, DateTimeKind.Utc).AddTicks(4070),
                            ModeratorId = 2,
                            NewStatus = "Verified",
                            PreviousStatus = "Pending",
                            Reason = "Valid",
                            ReportId = 1
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.ReportVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsUpVote")
                        .HasColumnType("bit");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.HasIndex("UserId");

                    b.ToTable("ReportVotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsUpVote = true,
                            ReportId = 1,
                            UserId = 2,
                            VotedAt = new DateTime(2026, 4, 11, 16, 46, 48, 452, DateTimeKind.Utc).AddTicks(4070)
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EndLat")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("EndLng")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("EstimatedDistance")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("EstimatedDuration")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("StartLat")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("StartLng")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("RouteId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            CreatedAt = new DateTime(2026, 4, 11, 16, 46, 48, 452, DateTimeKind.Utc).AddTicks(4070),
                            EndLat = 31.7054m,
                            EndLng = 35.2024m,
                            EstimatedDistance = 25.5m,
                            EstimatedDuration = 0.6m,
                            StartLat = 31.9539m,
                            StartLng = 35.2061m
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeographicArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            SubscriptionId = 1,
                            Category = "Accident",
                            CreatedAt = new DateTime(2026, 4, 11, 16, 46, 48, 452, DateTimeKind.Utc).AddTicks(4070),
                            GeographicArea = "Qalandia",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 4, 11, 16, 46, 48, 452, DateTimeKind.Utc).AddTicks(4070),
                            Email = "admin@wasel.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "HASH1",
                            Role = "admin",
                            Username = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 4, 11, 16, 46, 48, 452, DateTimeKind.Utc).AddTicks(4070),
                            Email = "mod@wasel.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "HASH2",
                            Role = "moderator",
                            Username = "Moderator"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 4, 11, 16, 46, 48, 452, DateTimeKind.Utc).AddTicks(4070),
                            Email = "user1@wasel.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "HASH3",
                            Role = "citizen",
                            Username = "User1"
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.CheckpointStatusHistory", b =>
                {
                    b.HasOne("ProjectWasel.Models.Checkpoint", "Checkpoint")
                        .WithMany("StatusHistory")
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checkpoint");
                });

            modelBuilder.Entity("ProjectWasel.Models.Incident", b =>
                {
                    b.HasOne("ProjectWasel.Models.Checkpoint", "Checkpoint")
                        .WithMany("Incidents")
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectWasel.Models.User", "CreatedByUser")
                        .WithMany("CreatedIncidents")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectWasel.Models.User", null)
                        .WithMany("VerifiedIncidents")
                        .HasForeignKey("UserId");

                    b.Navigation("Checkpoint");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ProjectWasel.Models.RefreshToken", b =>
                {
                    b.HasOne("ProjectWasel.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectWasel.Models.Report", b =>
                {
                    b.HasOne("ProjectWasel.Models.Incident", "Incident")
                        .WithMany("Reports")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectWasel.Models.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Incident");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectWasel.Models.ReportAuditLog", b =>
                {
                    b.HasOne("ProjectWasel.Models.User", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWasel.Models.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moderator");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ProjectWasel.Models.ReportVote", b =>
                {
                    b.HasOne("ProjectWasel.Models.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWasel.Models.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectWasel.Models.Subscription", b =>
                {
                    b.HasOne("ProjectWasel.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectWasel.Models.Checkpoint", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("ProjectWasel.Models.Incident", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("ProjectWasel.Models.User", b =>
                {
                    b.Navigation("CreatedIncidents");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reports");

                    b.Navigation("Subscriptions");

                    b.Navigation("VerifiedIncidents");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
