// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectWasel.Data;

#nullable disable

namespace ProjectWasel.Migrations
{
    [DbContext(typeof(WaselContext))]
    [Migration("20260321203251_FixPostgresSchema")]
    partial class FixPostgresSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectWasel.Models.Checkpoint", b =>
                {
                    b.Property<int>("CheckpointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CheckpointId"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CheckpointId");

                    b.ToTable("Checkpoints");

                    b.HasData(
                        new
                        {
                            CheckpointId = 1,
                            LastUpdated = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760),
                            Latitude = 31.9539m,
                            Longitude = 35.2061m,
                            Name = "Qalandia",
                            Status = "active"
                        },
                        new
                        {
                            CheckpointId = 2,
                            LastUpdated = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760),
                            Latitude = 31.7054m,
                            Longitude = 35.2024m,
                            Name = "Bethlehem 300",
                            Status = "delayed"
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.CheckpointStatusHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CheckpointId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HistoryId");

                    b.HasIndex("CheckpointId");

                    b.ToTable("CheckpointStatusHistories");

                    b.HasData(
                        new
                        {
                            HistoryId = 1,
                            ChangedAt = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760),
                            CheckpointId = 1,
                            Status = "active"
                        },
                        new
                        {
                            HistoryId = 2,
                            ChangedAt = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760),
                            CheckpointId = 2,
                            Status = "delayed"
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.ExternalData", b =>
                {
                    b.Property<int>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DataId"));

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DataId");

                    b.ToTable("ExternalData");

                    b.HasData(
                        new
                        {
                            DataId = 1,
                            ExternalKey = "weather_1",
                            FetchedAt = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760),
                            JsonData = "{\"temp\":25,\"status\":\"sunny\"}",
                            Source = "WeatherAPI"
                        },
                        new
                        {
                            DataId = 2,
                            ExternalKey = "map_1",
                            FetchedAt = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760),
                            JsonData = "{\"road\":\"open\"}",
                            Source = "OpenStreetMap"
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncidentId"));

                    b.Property<int?>("CheckpointId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("IncidentId");

                    b.HasIndex("CheckpointId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            IncidentId = 1,
                            CheckpointId = 1,
                            CreatedAt = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760),
                            CreatedByUserId = 3,
                            Description = "Minor accident",
                            Severity = "low",
                            Status = "verified",
                            Title = "Accident at Qalandia",
                            Type = "accident",
                            UpdatedAt = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760)
                        },
                        new
                        {
                            IncidentId = 2,
                            CheckpointId = 2,
                            CreatedAt = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760),
                            CreatedByUserId = 3,
                            Description = "Temporary closure",
                            Severity = "medium",
                            Status = "verified",
                            Title = "Closure at Bethlehem 300",
                            Type = "closure",
                            UpdatedAt = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760)
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ProjectWasel.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IncidentId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.HasKey("ReportId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            ReportId = 1,
                            Category = "Accident",
                            CreatedAt = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760),
                            Description = "Saw minor accident",
                            IncidentId = 1,
                            Latitude = 31.9539m,
                            Longitude = 35.2061m,
                            UserId = 3,
                            Votes = 5
                        },
                        new
                        {
                            ReportId = 2,
                            Category = "Closure",
                            CreatedAt = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760),
                            Description = "Road closed temporarily",
                            IncidentId = 2,
                            Latitude = 31.7054m,
                            Longitude = 35.2024m,
                            UserId = 2,
                            Votes = 3
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RouteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EndLat")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("EndLng")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("EstimatedDistance")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("EstimatedDuration")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("StartLat")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("StartLng")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.HasKey("RouteId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            CreatedAt = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760),
                            EndLat = 31.7054m,
                            EndLng = 35.2024m,
                            EstimatedDistance = 30.5m,
                            EstimatedDuration = 0.76m,
                            StartLat = 31.9539m,
                            StartLng = 35.2061m
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeographicArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            SubscriptionId = 1,
                            Category = "Accident",
                            CreatedAt = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760),
                            GeographicArea = "Qalandia",
                            UserId = 3
                        },
                        new
                        {
                            SubscriptionId = 2,
                            Category = "Closure",
                            CreatedAt = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760),
                            GeographicArea = "Bethlehem",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760),
                            Email = "ahmed@wasel.ps",
                            PasswordHash = "SECRET_HASH_ABC",
                            Role = "admin",
                            Username = "Ahmed_Admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760),
                            Email = "noor@wasel.ps",
                            PasswordHash = "SECRET_HASH_XYZ",
                            Role = "moderator",
                            Username = "Noor_Mod"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 3, 21, 20, 32, 51, 90, DateTimeKind.Utc).AddTicks(8760),
                            Email = "mohammad@wasel.ps",
                            PasswordHash = "SECRET_HASH_123",
                            Role = "citizen",
                            Username = "Mohammad_User"
                        });
                });

            modelBuilder.Entity("ProjectWasel.Models.CheckpointStatusHistory", b =>
                {
                    b.HasOne("ProjectWasel.Models.Checkpoint", "Checkpoint")
                        .WithMany("StatusHistory")
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checkpoint");
                });

            modelBuilder.Entity("ProjectWasel.Models.Incident", b =>
                {
                    b.HasOne("ProjectWasel.Models.Checkpoint", "Checkpoint")
                        .WithMany("Incidents")
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectWasel.Models.User", "CreatedByUser")
                        .WithMany("CreatedIncidents")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectWasel.Models.User", null)
                        .WithMany("VerifiedIncidents")
                        .HasForeignKey("UserId");

                    b.Navigation("Checkpoint");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ProjectWasel.Models.RefreshToken", b =>
                {
                    b.HasOne("ProjectWasel.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectWasel.Models.Report", b =>
                {
                    b.HasOne("ProjectWasel.Models.Incident", "Incident")
                        .WithMany("Reports")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectWasel.Models.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Incident");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectWasel.Models.Subscription", b =>
                {
                    b.HasOne("ProjectWasel.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectWasel.Models.Checkpoint", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("ProjectWasel.Models.Incident", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("ProjectWasel.Models.User", b =>
                {
                    b.Navigation("CreatedIncidents");

                    b.Navigation("Reports");

                    b.Navigation("Subscriptions");

                    b.Navigation("VerifiedIncidents");
                });
#pragma warning restore 612, 618
        }
    }
}
